version: "3"

services:
  sonarqube:
    image: sonarqube:9.9.0-community
    environment:
    - SONAR_JDBC_URL=jdbc:postgresql://postgres/sonarqube?currentSchema=sonarqube
    - SONAR_JDBC_USERNAME=postgres
    - SONAR_JDBC_PASSWORD=postgres
    ports:
    - 9000:9000
  postgres:
    image: postgres:12-alpine3.17
    environment:
    - POSTGRES_DB=sonarqube
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    ports:
    - 5432:5432
