version: '3'

services:
  mariadb:
    image: mariadb:11.2.2-jammy
    environment:
      - MARIADB_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    volumes:
      - mariadb_db:/var/lib/mysql

volumes:
  mariadb_db: {}
