version: '3'

services:
  opensearch:
    image: opensearchproject/opensearch:2.4.1
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300

  opensearch-dashboard:
    image: opensearchproject/opensearch-dashboards:2.4.1
    environment:
      - OPENSEARCH_HOSTS=["https://opensearch:9200"]
    ports:
      - 5601:5601
    depends_on:
      - opensearch

  fluent-bit:
    image: fluent/fluent-bit:1.9.10
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    depends_on:
      - opensearch
  