version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      discovery.type: single-node
    ports:
      - 9200:9200

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:8.11.3-arm64
    ports:
      - 5044:5044
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.3
    environment:
      ELASTICSEARCH_HOSTS: http://es1:9200
    ports:
      - 5601:5601
