version: '3'

services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.13
    ports:
      - 3279:2379
      - 2380:2380
      - 4001:4001
    volumes:
      - /usr/share/ca-certificates/:/etc/ssl/certs:ro
    command:
      - /usr/local/bin/etcd
      - --name=etcd
      - --advertise-client-urls=http://etcd:2379
      - --initial-advertise-peer-urls=http://etcd:2380
      - --listen-client-urls=http://0.0.0.0:2379
      # - --listen-peer-urls=http://etcd:2380
      - --initial-cluster=etcd=http://etcd:2380
      - --initial-cluster-state=new

  apisix:
    image: apache/apisix:3.9.1-debian
    ports:
      - 9080:9080
      - 9091:9091
      - 9443:9443
    volumes:
      - ./api-conf/config.yaml:/usr/local/apisix/conf/config.yaml
    depends_on:
      - etcd

  apisix-dashboard:
    image: apache/apisix-dashboard:3.0.1-alpine
    ports:
      - 9000:9000
    volumes:
      - ./dashboard-conf/config.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
    depends_on:
      - apisix

  coffee:
    image: nginxdemos/nginx-hello:plain-text

  tea:
    image: nginxdemos/nginx-hello:plain-text
