version: '3'

services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.5.0
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'

  prometheus:
    image: quay.io/prometheus/prometheus:v2.42.0
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-lifecycle"
      - "--storage.tsdb.retention.time=7d"

  grafana:
    image: grafana/grafana:9.3.6-ubuntu
    ports:
      - 3000:3000

volumes:
  prometheus_data:
