version: '3'

services:
  postgres:
    image: postgres:12.14-alpine3.17
    environment:
      - POSTGRES_DB=sonarqube
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  sonarqube:
    image: sonarqube:9.9.0-community
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      - SONAR_JDBC_URL=jdbc:postgresql://postgres:5432/sonarqube
      - SONAR_JDBC_USERNAME=postgres
      - SONAR_JDBC_PASSWORD=postgres
    ports:
      - 9000:9000
    depends_on:
      - postgres
