version: '3'
services:
  dragonflydb:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ulimits:
      memlock: -1
    ports:
      - 6379:6379
    command: sh -c "/usr/local/bin/dragonfly --logtostderr --proactor_threads=1 --maxmemory=2gb"
