version: '3'

services:
  # mongo:
  #   image: mongo:6.0.9-jammy
  #   ports:
  #     - 27017:27017
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=admin
  #     - MONGO_INITDB_ROOT_PASSWORD=admin
  #   volumes:
  #     - ./mongodb-keyfile:/opt/keyfile
  #   command: --keyFile /opt/keyfile --replSet rs0 --oplogSize 100 --bind_ip 0.0.0.0

  # postgres:
  #   image: debezium/example-postgres:2.3
  #   ports:
  #     - 5432:5432
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres

  # mysql:
  #   image: quay.io/debezium/example-mysql:2.3
  #   ports:
  #     - 3306:3306
  #   environment:
  #     MYSQL_ROOT_PASSWORD: debezium
  #     MYSQL_USER: mysqluser
  #     MYSQL_PASSWORD: mysqlpw

  # kafka:
  #   image: bitnami/kafka:3.4.1
  #   ports:
  #     - 9092:9092
  #   environment:
  #   - KAFKA_ENABLE_KRAFT=yes
  #   - KAFKA_CFG_NODE_ID=1
  #   - KAFKA_CFG_PROCESS_ROLES=broker,controller
  #   - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
  #   - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
  #   - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
  #   - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
  #   - KAFKA_BROKER_ID=1
  #   - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
  #   - ALLOW_PLAINTEXT_LISTENER=yes

  # kafdrop:
  #   image: obsidiandynamics/kafdrop
  #   environment:
  #     - KAFKA_BROKERCONNECT=kafka:9092
  #     - JVM_OPTS=-Xms16M -Xmx512M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify
  #   ports:
  #     - 9000:9000
  #   depends_on:
  #     - kafka

  redpanda:
    image: redpandadata/redpanda:v23.1.17
    command:
      - redpanda
      - start
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --node-id 0
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      - --advertise-pandaproxy-addr internal://redpanda:8082,external://localhost:18082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
      - --rpc-addr redpanda:33145
      - --advertise-rpc-addr redpanda:33145
      - --default-log-level=info

  redpanda-console:
    image: redpandadata/console:v2.3.1
    ports:
      - 8080:8080
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda:9092"]
          schemaRegistry:
            enabled: true
            urls: ["http://redpanda:8081"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda:9644"]
    entrypoint: /bin/sh
    command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml; /app/console'
    depends_on:
      - redpanda

  connect:
    image: quay.io/debezium/connect:2.3
    ports:
      - 8083:8083
    environment:
      - GROUP_ID=1
      # - BOOTSTRAP_SERVERS=kafka:9092
      - BOOTSTRAP_SERVERS=redpanda:9092
      - CONFIG_STORAGE_TOPIC=connect_configs
      - OFFSET_STORAGE_TOPIC=connect_offsets
      - STATUS_STORAGE_TOPIC=connect_statuses
    depends_on:
      # - kafka
      - redpanda
      - mongo
