version: '3'

services:
  mongodb:
    image: mongo:5.0.15-focal
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./mongodb-keyfile:/opt/keyfile
    command: --keyFile /opt/keyfile --replSet rs0
