version: '3'

services:
  collector:
    image: jaegertracing/jaeger-collector:1.18.0
    restart: always
    environment:
      - "SPAN_STORAGE_TYPE=elasticsearch"
      - "ES_SERVER_URLS=http://elasticsearch:9200"
    ports:
      - 14268:14268
    depends_on:
      - elasticsearch

  query:
    image: jaegertracing/jaeger-query:1.18.0
    restart: always
    environment:
      - "SPAN_STORAGE_TYPE=elasticsearch"
      - "ES_SERVER_URLS=http://elasticsearch:9200"
    ports:
      - 16686:16686
    depends_on:
      - elasticsearch

  agent:
    image: jaegertracing/jaeger-agent:1.18.0
    restart: always
    ports:
      - 6831:6831/udp
    command:
      - --reporter.grpc.host-port=collector:14250
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3-amd64
    restart: always
    ports: 
      - 9200:9200
    environment: 
      - "discovery.type=single-node"
      - "node.name=elasticsearch"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes: 
      - elasticsearch:/usr/share/elasticsearch/config

  diagram:
    image: jaegertracing/spark-dependencies:latest
    environment:
      - "STORAGE=elasticsearch"
      - "ES_NODES=http://elasticsearch:9200"
      - "JAVA_OPTS=-Xmx512m"

volumes: 
  elasticsearch: