version: '3'

services: 
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3-amd64
    restart: always
    ports: 
      - 9200:9200
    environment: 
      - "discovery.type=single-node"
      - "node.name=elasticsearch"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes: 
      - elasticsearch:/usr/share/elasticsearch/config

  apm:
    image: docker.elastic.co/apm/apm-server:7.9.3
    restart: always
    ports: 
      - 8200:8200
    command: >
       apm-server -e
         -E output.elasticsearch.hosts=["elasticsearch:9200"]

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.3
    restart: always
    ports: 
      - 5601:5601
    depends_on: 
      - elasticsearch

volumes: 
  elasticsearch:
  apm-server: