***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***   http://www.apache.org/licenses/LICENSE-2.0
***REMOVED***
***REMOVED*** Unless required by applicable law or agreed to in writing,
***REMOVED*** software distributed under the License is distributed on an
***REMOVED*** "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
***REMOVED*** KIND, either express or implied.  See the License for the
***REMOVED*** specific language governing permissions and limitations
***REMOVED*** under the License.
***REMOVED***

***REMOVED*** Basic Airflow cluster configuration for CeleryExecutor with Redis and PostgreSQL.
***REMOVED***
***REMOVED*** WARNING: This configuration is for local development. Do not use it in a production deployment.
***REMOVED***
***REMOVED*** This configuration supports basic configuration using environment variables or an .env file
***REMOVED*** The following variables are supported:
***REMOVED***
***REMOVED*** AIRFLOW_IMAGE_NAME           - Docker image name used to run Airflow.
***REMOVED***                                Default: apache/airflow:2.5.1
***REMOVED*** AIRFLOW_UID                  - User ID in Airflow containers
***REMOVED***                                Default: 50000
***REMOVED*** AIRFLOW_PROJ_DIR             - Base path to which all the files will be volumed.
***REMOVED***                                Default: .
***REMOVED*** Those configurations are useful mostly in case of standalone testing/running Airflow in test/try-out mode
***REMOVED***
***REMOVED*** _AIRFLOW_WWW_USER_USERNAME   - Username for the administrator account (if requested).
***REMOVED***                                Default: airflow
***REMOVED*** _AIRFLOW_WWW_USER_PASSWORD   - Password for the administrator account (if requested).
***REMOVED***                                Default: airflow
***REMOVED*** _PIP_ADDITIONAL_REQUIREMENTS - Additional PIP requirements to add when starting all containers.
***REMOVED***                                Default: ''
***REMOVED***
***REMOVED*** Feel free to modify this file to suit your needs.
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
  ***REMOVED*** In order to add custom dependencies or upgrade provider packages you can use your extended image.
  ***REMOVED*** Comment the image line, place your Dockerfile in the directory where you placed the docker-compose.yaml
  ***REMOVED*** and uncomment the "build" line below, Then run `docker-compose build` to build the images.
***REMOVED***
  ***REMOVED*** build: .
***REMOVED***
  ***REMOVED***-env
***REMOVED***
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    ***REMOVED*** For backward compatibility, with Airflow <2.3
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
    AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
    _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS:-}
***REMOVED***
    - ${AIRFLOW_PROJ_DIR:-.}/dags:/opt/airflow/dags
***REMOVED***
***REMOVED***
***REMOVED***

***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
      - 8080:8080
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***

***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***

***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
  ***REMOVED***
  ***REMOVED***-env
      ***REMOVED*** Required to handle warm shutdown of the celery workers properly
      ***REMOVED*** See https://airflow.apache.org/docs/docker-stack/entrypoint.html***REMOVED***signal-propagation
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***

***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED*** ["CMD-SHELL", 'airflow jobs check --job-type TriggererJob --hostname "$${HOSTNAME}"']
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***

***REMOVED***
***REMOVED***
***REMOVED***
    ***REMOVED*** yamllint disable rule:line-length
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED*** -e "\033[1;31mERROR!!!: Too old Airflow version $${airflow_version}!\e[0m"
***REMOVED*** "The minimum Airflow version supported: $${min_airflow_version}. Only use this or higher!"
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED*** -e "\033[1;33mWARNING!!!: AIRFLOW_UID not set!\e[0m"
***REMOVED*** "If you are on Linux, you SHOULD follow the instructions below to set "
***REMOVED*** "AIRFLOW_UID environment variable, otherwise files will be owned by root."
***REMOVED*** "For other operating systems you can get rid of the warning with manually created .env file:"
***REMOVED*** "    See: https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html***REMOVED***setting-the-right-airflow-user"
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED*** -e "\033[1;33mWARNING!!!: Not enough memory available for Docker.\e[0m"
***REMOVED*** "At least 4GB of memory required. You have $$(numfmt --to iec $$((mem_available * one_meg)))"
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED*** -e "\033[1;33mWARNING!!!: Not enough CPUS available for Docker.\e[0m"
***REMOVED*** "At least 2 CPUs recommended. You have $${cpus_available}"
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED*** -e "\033[1;33mWARNING!!!: Not enough Disk space available for Docker.\e[0m"
***REMOVED*** "At least 10 GBs recommended. You have $$(numfmt --to iec $$((disk_available * 1024 )))"
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED*** -e "\033[1;33mWARNING!!!: You have not enough resources to run Airflow (see above)!\e[0m"
***REMOVED*** "Please follow the instructions to increase amount of resources available:"
***REMOVED*** "   https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html***REMOVED***before-you-begin"
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
    ***REMOVED*** yamllint enable rule:line-length
  ***REMOVED***
  ***REMOVED***-env
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
  ***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***

***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
  ***REMOVED***
  ***REMOVED***-env
***REMOVED***
    ***REMOVED*** Workaround for entrypoint issue. See: https://github.com/apache/airflow/issues/16252
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***

  ***REMOVED*** You can enable flower by adding "--profile flower" option e.g. docker-compose --profile flower up
  ***REMOVED*** or by explicitly targeted on the command line e.g. docker-compose up flower.
  ***REMOVED*** See: https://docs.docker.com/compose/profiles/
***REMOVED***
***REMOVED***
***REMOVED*** celery flower
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED*** ["CMD", "curl", "--fail", "http://localhost:5555/"]
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***

***REMOVED***
***REMOVED***

***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
