version: '3'

services: 
  jenkins:
    image: jenkins/jenkins:2.235.1-lts-alpine
    restart: always
    ports: 
      - 8080:8080
    volumes: 
      - jenkins:/var/jenkins_home

  influxdb:
    image: influxdb:1.8.0-alpine
    restart: always
    ports: 
      - 8086:8086
    environment: 
      - "INFLUXDB_DB=jenkins"
      - "INFLUXDB_HTTP_AUTH_ENABLED=true"
      - "INFLUXDB_ADMIN_USER=jenkins"
      - "INFLUXDB_ADMIN_PASSWORD=jenkins"
      
  grafana:
    image: grafana/grafana:7.0.3
    restart: always
    ports:
      - 3000:3000
    volumes: 
      - grafana:/usr/share/grafana

volumes: 
  jenkins:
  grafana:
  # influxdb: