version: '3'

services:
  minio:
    image: quay.io/minio/minio:RELEASE.2023-10-14T05-17-22Z
    ports:
      - 9000:9000
      - 9090:9090
    environment:
      - MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE
      - MINIO_ROOT_PASSWORD=WJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    volumes:
      - data:/data
    command: server /data --console-address ":9090"

volumes:
  data: {}