version: '3'

services:
  loki:
    image: grafana/loki:2.7.4
    volumes:
      - ./local-config.yaml:/etc/loki/local-config.yaml
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
  promtail:
    image: grafana/promtail:2.7.4
    volumes:
      - ./config.yml:/etc/loki/local-config.yaml
      - /var/log:/var/log
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/config.yml

  grafana:
    image: grafana/grafana:9.3.6-ubuntu
    ports:
      - 3000:3000
