version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.7.4
    ports:
      - "23100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.7.4
    volumes:
      - ./promtail:/etc/promtail
#      - /var/log:/var/log
#      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "23000:3000"
    networks:
      - loki

