version: '3'

services:
  vault:
    image: hashicorp/vault:1.14.8
    environment:
      VAULT_ADDR: http://0.0.0.0:8200
    ports:
      - 8200:8200
    volumes:
      - vault_data:/vault/data
      - ./vault.json:/vault/config/vault.json
    entrypoint: vault server -config=/vault/config/vault.json
    cap_add:
      - IPC_LOCK

volumes:
  vault_data: {}
