server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
#- job_name: system
#  static_configs:
#  - targets:
#      - localhost
#    labels:
#      job: varlogs
#      __path__: /var/log/*log

#- job_name: containers
#  static_configs:
#  - targets:
#      - localhost
#    labels:
#      job: containerlogs
#      __path__: /var/lib/docker/containers/*/*log

- job_name: docker 
  docker_sd_configs:
  - host: unix:///var/run/docker.sock
    refresh_interval: 15s
  relabel_configs:
  - source_labels: ['__meta_docker_container_name']
    regex: '/(.*)'
    target_label: 'container'
