version: '3'

services:
  mysql:
    image: mysql:5.7.32
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin

  wordpress:
    image: wordpress:5.2-php7.2-fpm-alpine
    environment:
      - WORDPRESS_DB_HOST=mysql:3306
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=admin
      - WORDPRESS_DB_PASSWORD=admin
    volumes:
      - wordpress_web:/var/www/html
    depends_on:
      - mysql

  nginx:
    image: nginx:1.16-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - wordpress_web:/var/www/html
      - ./conf:/etc/nginx/conf.d
    depends_on:
      - wordpress

volumes:
  wordpress_web:
  mysql_data: